config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookmarks, only: :destroy
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
 
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]
  def index
    @lists = List.all
  end

  def show
  end
  
  def new
    @list = List.new
  end

  def create
    @list= List.new(list_params)
    if @list.save
      redirect_to @list, notice: "Made List"
    else
      render :new
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end
  
  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show]

  def index
    @movies = Movie.all
  end

  def show
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1> Your Lists </h1>

<%= link_to "Add a new list",  new_list_path%>

<ul>
<% @lists.each do |list|%>
<li><%= link_to list.name, list_path(list) %></li>
<% end %>
</ul>

<%= link_to "see all movies", movies_path %>

app/views/lists/new.html.erb
<h1> Create your list </h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<%= link_to "add a movie", new_list_bookmark_path %>

<%= link_to "go back", lists_path %>

app/views/movies/index.html.erb
<h1> Top 20 Movies According To Someone </h1>

<ul>
<% @movies.each do |movie| %>
 <li><%=link_to movie.title, movie_path(movie) %> </li>
<% end %>
</ul>

<%= link_to "See your lists", lists_path %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<p><strong>synopsis</strong><br><%= @movie.overview %></p>
<p>rating: <%= @movie.rating %>/5</p>

<%= link_to "go back", movies_path %>